### ISSUE TITLE
Build broken with unresolvable `sbt` dependencies

### ISSUE THREAD

**Issue by valgog** [zalando/play-swagger#37]
The build is currently broken with unresolvable dependencies. I would suggest to block the ability to push the master branch if Travis-CI does not pass. It makes no sense to have a failing master.

Currently there are two problems. The first, currently reported by travis-ci, is with scalaz-streams dependency is not resolvable. This can be solved by adding 
```scala
"scalaz-bintray" at "https://dl.bintray.com/scalaz/releases"
```
to `build.sbt`, but afterwords, there comes the error with resolving 

    sbt.ResolveException: unresolved dependency: me.andrz.jackson#jackson-json-reference;0.1.2: not found

**Comment by nmcb** [comment]
@valgog You are right of course, we're currently committing directly against master in order to fix dependencies iot. release from bintray on the upcoming swagger 0.1 release. Making the master stable for the release next Tuesday directly on the master. After that we'll move to PR merge towards master only, as that's the moment that we need the master to be stable i/b releases.

Sorry to be in your way at this moment, but (as you're enjoy working on play-swagger on your free Sunday...)  We're working on a activator template to work in conjunction with the bintray published release. Have a look if you have the time and are interested. All feedback and help up to the workshop coming Tuesday is welcome: https://github.com/zalando/play-swagger-service

**Comment by valgog** [comment]
@mmcb I understand. Yes, I just wanted to try the project out... :) will wait for your presentation :)

**Comment by valgog** [comment]
I have opened an PR with the needed resolvers

**Comment by nmcb** [comment]
Thanks! That's really appreciated as the activator template with the binary bintray release will be the primary contact point for users of the plugin starting from Tuesday. Mind that Slava and I are heavily working on it as we speak, so we might break a few things now and then up to that moment.

**Comment by nmcb** [comment]
Fixed by PR41
